### ISSUE TITLE
[QUESTION] How to use CaptchaSolver if JD2 runs in a docker container on a QNAP NAS?

### ISSUE THREAD

**Issue by cn-tools** [cracker0dks/CaptchaSolver#14]
Hello @cracker0dks!

I'm running JD2 from [jlesage](https://github.com/jlesage/docker-jdownloader-2) as a Docker container on my QNAP NAS inside the Container Station.

Unfortunately, i haven't found anything in the web that could help me to use your "app".

Do you have any tips and tricks to use your code within my constellation?

best regards

**Comment by cracker0dks** [comment]
Hey @cn-tools 
you need to build your on Docker Container. You could take the dockerfile from jlesage and modifiy it to install node inside and also copy this captcha solver inside the container.
cheers

**Comment by Thermionix** [comment]
I had to recompile the darknet binary within the docker container due to the alpine image using musl libs and not gcc
I also tried with adding `libexecinfo-dev` but just ended up removing backtrace

Attach to your container name with a shell; `docker exec -it jdownloader sh`

````
apk add --update --no-cache alpine-sdk                
cd /config/tools/
git clone https://github.com/AlexeyAB/darknet
cd darknet
sed -i '/#include <execinfo.h>/d' src/utils.c
sed -i '/^void log_backtrace()$/,/^}$/d' src/utils.c
sed -i '/log_backtrace();/d' src/utils.c
make
cp darknet ../offlineCaptchaSolver/darknet64/

cd /config/tools/offlineCaptchaSolver
./checkdeps.sh
````

**Comment by Thermionix** [comment]
docker-compose.yml 
````
version: '3'
services:
  jdownloader-2:
    container_name: jdownloader
    image: jlesage/jdownloader-2
    ports:
      - "5800:5800"
    volumes:
      - /var/lib/jdownloader:/config
      - /tank/downloads/jdownloader:/output
    environment:
      - TZ=Australia/Brisbane
      - USER_ID=1000
      - GROUP_ID=985
      - VNC_LISTENING_PORT=-1
      - INSTALL_PACKAGES=nodejs npm
  ````
